package edu.szebo.ppke.survival;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Ideapad' at '2017.03.27. 21:15' with Gradle 2.13
 *
 * @author Ideapad, @date 2017.03.27. 21:15
 */
public class AStarTest {
    @Test public void testSomeLibraryMethod() {
       //  Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", false); //classUnderTest.someLibraryMethod());
    }
}
